-- 007_more_airports.sql

-- Additional airports for popular European destinations
INSERT INTO airport (iata, name, city, country, tz) VALUES
-- Spain (extended)
('SVQ','San Pablo','Seville','Spain','Europe/Madrid'),
('VLC','Valencia','Valencia','Spain','Europe/Madrid'),
('BIO','Bilbao','Bilbao','Spain','Europe/Madrid'),
('SDR','Seve Ballesteros-Santander','Santander','Spain','Europe/Madrid'),
('SCQ','Santiago-Rosalía de Castro','Santiago de Compostela','Spain','Europe/Madrid'),
('REU','Reus','Reus','Spain','Europe/Madrid'),
('MAH','Menorca','Mahon','Spain','Europe/Madrid'),
('XRY','Jerez','Jerez de la Frontera','Spain','Europe/Madrid'),
('LEI','Almería','Almería','Spain','Europe/Madrid'),
('TFN','Tenerife North','San Cristóbal de La Laguna','Spain','Atlantic/Canary'),
('TFS','Tenerife South','Granadilla de Abona','Spain','Atlantic/Canary'),
('LPA','Gran Canaria','Las Palmas','Spain','Atlantic/Canary'),
('ACE','Lanzarote','Arrecife','Spain','Atlantic/Canary'),
('FUE','Fuerteventura','Puerto del Rosario','Spain','Atlantic/Canary'),
('SPC','La Palma','Santa Cruz de La Palma','Spain','Atlantic/Canary'),
-- Portugal
('LIS','Humberto Delgado','Lisbon','Portugal','Europe/Lisbon'),
('OPO','Francisco Sá Carneiro','Porto','Portugal','Europe/Lisbon'),
('FAO','Faro','Faro','Portugal','Europe/Lisbon'),
('FNC','Cristiano Ronaldo Madeira','Funchal','Portugal','Atlantic/Madeira'),
('PDL','Joao Paulo II','Ponta Delgada','Portugal','Atlantic/Azores'),
('TER','Lajes','Terceira','Portugal','Atlantic/Azores'),
-- North America (United States & Canada)
('ATL','Hartsfield Jackson Atlanta International Airport','Atlanta','United States','America/New_York'),
('ORD','Chicago O''Hare International Airport','Chicago','United States','America/Chicago'),
('DFW','Dallas Fort Worth International Airport','Dallas-Fort Worth','United States','America/Chicago'),
('SFO','San Francisco International Airport','San Francisco','United States','America/Los_Angeles'),
('DEN','Denver International Airport','Denver','United States','America/Denver'),
('MSP','Minneapolis-Saint Paul International Airport / Wold-Chamberlain Field','Minneapolis','United States','America/Chicago'),
('DTW','Detroit Metropolitan Wayne County Airport','Detroit','United States','America/Detroit'),
('LAS','Harry Reid International Airport','Las Vegas','United States','America/Los_Angeles'),
('EWR','Newark Liberty International Airport','Newark','United States','America/New_York'),
('PHX','Phoenix Sky Harbor International Airport','Phoenix','United States','America/Phoenix'),
('IAH','George Bush Intercontinental Houston Airport','Houston','United States','America/Chicago'),
('STL','St. Louis Lambert International Airport','St Louis','United States','America/Chicago'),
('MCO','Orlando International Airport','Orlando','United States','America/New_York'),
('BOS','Logan International Airport','Boston','United States','America/New_York'),
('PHL','Philadelphia International Airport','Philadelphia','United States','America/New_York'),
('LGA','LaGuardia Airport','New York','United States','America/New_York'),
('CVG','Cincinnati Northern Kentucky International Airport','Cincinnati / Covington','United States','America/New_York'),
('HNL','Daniel K Inouye International Airport','Honolulu','United States','Pacific/Honolulu'),
('CLT','Charlotte Douglas International Airport','Charlotte','United States','America/New_York'),
('SLC','Salt Lake City International Airport','Salt Lake City','United States','America/Denver'),
('IAD','Washington Dulles International Airport','Dulles','United States','America/New_York'),
('TPA','Tampa International Airport','Tampa','United States','America/New_York'),
('SAN','San Diego International Airport','San Diego','United States','America/Los_Angeles'),
('DCA','Ronald Reagan Washington National Airport','Washington','United States','America/New_York'),
('CLE','Cleveland Hopkins International Airport','Cleveland','United States','America/New_York'),
('YUL','Montreal / Pierre Elliott Trudeau International Airport','Montreal','Canada','America/Toronto'),
('CUN','Cancun International Airport','Cancun','Mexico','America/Cancun'),
('MEX','Benito Juarez International Airport','Mexico City','Mexico','America/Mexico_City'),
('PTY','Tocumen International Airport','Tocumen','Panama','America/Panama'),
('PUJ','Punta Cana International Airport','Punta Cana','Dominican Republic','America/Santo_Domingo'),
('SDQ','Las Americas International Airport','Santo Domingo','Dominican Republic','America/Santo_Domingo'),
('HAV','Jose Marti International Airport','Havana','Cuba','America/Havana'),
-- Europe
('ZRH','Zurich Airport','Zurich','Switzerland','Europe/Zurich'),
('BRU','Brussels Airport','Zaventem','Belgium','Europe/Brussels'),
('MAN','Manchester Airport','Manchester','United Kingdom','Europe/London'),
('CPH','Copenhagen Airport','Copenhagen','Denmark','Europe/Copenhagen'),
('ARN','Stockholm-Arlanda Airport','Stockholm','Sweden','Europe/Stockholm'),
('DUS','Dusseldorf Airport','Dusseldorf','Germany','Europe/Berlin'),
-- Asia-Pacific
('HKG','Hong Kong International Airport','Hong Kong','Hong Kong','Asia/Hong_Kong'),
('KIX','Kansai International Airport','Osaka','Japan','Asia/Tokyo'),
('FUK','Fukuoka Airport','Fukuoka','Japan','Asia/Tokyo'),
('CTS','New Chitose Airport','Sapporo','Japan','Asia/Tokyo'),
('TPE','Taiwan Taoyuan International Airport','Taoyuan','Taiwan','Asia/Taipei'),
('SHA','Shanghai Hongqiao International Airport','Shanghai','China','Asia/Shanghai'),
('BNE','Brisbane International Airport','Brisbane','Australia','Australia/Brisbane'),
('PER','Perth Airport','Perth','Australia','Australia/Perth'),
-- Latin America
('BOG','El Dorado International Airport','Bogota','Colombia','America/Bogota'),
('SCL','Arturo Merino Benitez International Airport','Santiago','Chile','America/Santiago'),
('LIM','Jorge Chavez International Airport','Lima','Peru','America/Lima'),
('EZE','Minister Pistarini International Airport','Buenos Aires','Argentina','America/Argentina/Buenos_Aires'),
-- Middle East & Africa
('DOH','Hamad International Airport','Doha','Qatar','Asia/Qatar'),
('LOS','Murtala Muhammed International Airport','Lagos','Nigeria','Africa/Lagos'),
('ACC','Kotoka International Airport','Accra','Ghana','Africa/Accra'),
('JNB','O. R. Tambo International Airport','Johannesburg','South Africa','Africa/Johannesburg'),
('CPT','Cape Town International Airport','Cape Town','South Africa','Africa/Johannesburg'),
('NBO','Jomo Kenyatta International Airport','Nairobi','Kenya','Africa/Nairobi'),
('ADD','Addis Ababa Bole International Airport','Addis Ababa','Ethiopia','Africa/Addis_Ababa'),
('CMN','Mohammed V International Airport','Casablanca','Morocco','Africa/Casablanca'),
('RAK','Marrakesh Menara Airport','Marrakech','Morocco','Africa/Casablanca')
ON CONFLICT (iata) DO NOTHING;

