version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deliverty
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      # run our .sql on first boot
      - ../backend/migrations:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  dbdata:
