name: Deploy to Contabo

on:
  push:
    branches:
      - main    # или master, если у тебя так называется
    paths-ignore:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /srv/apps/deliverty
            git pull

            # На всякий случай — подтянуть образы (если когда-нибудь начнёшь пушить в регистр)
            docker compose pull || true

            # Если хочешь всегда пересобирать всё:
            docker compose up -d --build
